[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "__PROJECT_NAME__"
version = "0.1.1"
description = "__PROJECT_NAME__ generated by kmvpy"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kmvpy>=0.2.3",
    "cryptography>=46.0.0",
    "SQLAlchemy>=2.0,<3",
    "aiomysql>=0.3.2,<0.4",
]

[project.optional-dependencies]
test = [
    "pytest",
]
mysql = [
    "aiomysql",
]
postgresql = [
    "asyncpg",
]
sqlite = [
    "aiosqlite",
]
all = [
    "pytest",
    "aiomysql",
    "asyncpg",
    "aiosqlite",
]

[tool.setuptools]
packages = {find = {where = ["."], exclude = ["app", "app.*"]}}
include-package-data = true
zip-safe = false
