# __PROJECT_NAME__

> 中文 | [English](#english)

---

## 中文

本项目由 `kmvpy create` 生成。真实 Python 工程位于 `__PY_PROJECT_NAME__/` 目录下。

### 快速开始

推荐直接在 Cursor 打开生成后的外层 workspace 根目录，以复用生成器预置的 `.vscode/settings.json` 和 `.vscode/launch.json`。

首次进入项目后，创建虚拟环境并安装运行依赖：

```bash
cd __PY_PROJECT_NAME__
python -m venv .venv
source .venv/bin/activate   # Windows 请使用: .venv\Scripts\activate
pip install -e ".[postgresql]"
```

然后在 Cursor 中执行 `Python: Select Interpreter`，选择 `__PY_PROJECT_NAME__/.venv`，并启动应用：

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
python app/run.py
```

---

<a name="english"></a>

## English

This project was generated by `kmvpy create`. The Python project lives in the `__PY_PROJECT_NAME__/` directory.

### Quick Start

Open the generated outer workspace root in Cursor so the preset `.vscode/settings.json` and `.vscode/launch.json` remain available.

Create a virtual environment and install the runtime dependencies:

```bash
cd __PY_PROJECT_NAME__
python -m venv .venv
source .venv/bin/activate
pip install -e ".[postgresql]"
```

Run `Python: Select Interpreter` in Cursor, select `__PY_PROJECT_NAME__/.venv`, and start the application:

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
python app/run.py
```
