# __PROJECT_NAME__

> 中文 | [English](#english)

---

## 中文

本项目由 `kmvpy create` 生成。真实 Python 工程位于 `__PY_PROJECT_NAME__/` 目录下。

### 快速开始

推荐直接在 Cursor 打开生成后的外层 workspace 根目录，而不是只打开 `__PY_PROJECT_NAME__/`。
这样可以直接复用生成器预置的 `.vscode/settings.json` 和 `.vscode/launch.json`。

首次进入项目后，先创建虚拟环境并安装依赖：

```bash
cd __PY_PROJECT_NAME__
python -m venv .venv
source .venv/bin/activate   # Windows 请使用: .venv\Scripts\activate
pip install -e ".[test,sqlite]"
```

然后在 Cursor 中选择这个解释器：

1. 打开命令面板
2. 执行 `Python: Select Interpreter`
3. 选择 `__PY_PROJECT_NAME__/.venv`

启动应用：

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
python app/run.py
```

### 冒烟测试

生成项目已内置 `app/st_test/` 冒烟测试目录，覆盖用户登录注册与资料接口。

这套测试框架的核心是：

- `pytest` 负责执行测试
- `StBasePyTest.data_driven` 把同名 YAML 用例转成参数化测试
- `TestClient` 直接调用 FastAPI 应用，不必额外手工启动服务
- `StExpect` 只校验必要字段，适合做接口冒烟测试

默认会以 `app/etc/develop/config.yaml` 为测试客户端配置来源，并使用其中的 `service.host/service.port` 构造请求地址。
用户相关测试会自动生成临时 SQLite 配置和临时数据库文件，因此本地可直接运行。

运行全部冒烟测试：

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pip install -e ".[test,sqlite]"
pytest app/st_test
```

只运行某一个用户测试：

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pytest app/st_test/test_user_opt_router.py -k test_email_login -q
```

查看详细输出：

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pytest app/st_test -vv
```

### 在 Cursor 中使用

推荐两种方式：

#### 1. 使用内置终端

这是最稳定的方式：

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pytest app/st_test -vv
```

#### 2. 使用测试面板

在 Cursor 中选好 `__PY_PROJECT_NAME__/.venv` 解释器后，可以直接在测试面板运行 `app/st_test` 下的测试。

如果没有发现测试或导入失败，优先检查：

- 当前打开的是不是外层 workspace 根目录
- 当前解释器是否为 `__PY_PROJECT_NAME__/.venv`
- 是否已安装 `pytest`
- 是否已安装 `aiosqlite`

### 文件约定

每个测试文件都要配一个同目录、同文件名的 YAML：

- `app/st_test/test_user_opt_router.py`
- `app/st_test/test_user_opt_router.yaml`

并且 YAML 顶层 key 必须和测试方法名一致。例如：

```python
@StBasePyTest.data_driven
def test_email_login(self, user_smoke_client, testdata: StTestCase):
    self.run_case(user_smoke_client, testdata)
```

对应 YAML：

```yaml
test_email_login:
  comment: 用户登录冒烟测试
  case_list:
    - comment: 使用已注册账号登录
      steps:
        - step_kid: STEP_EMAIL_LOGIN
          action: POST /api/user/email/login
          request:
            email: smoke_login@example.com
            password: "SmokePass123"
      expected:
        code: 0
```

约定说明：

- `step.action` 必须写成 `METHOD /uri`
- `request` 对 `POST` 会自动映射到 JSON 请求体
- `request` 对 `GET` 会自动映射到查询参数
- `expected.data` 只需要写你关心的关键字段

### 新增冒烟测试

新增一个接口冒烟测试时，推荐按下面步骤做：

1. 在 `app/st_test/` 下新增测试文件，例如 `test_order_router.py`
2. 在同目录新增 `test_order_router.yaml`
3. 让测试类继承 `StBasePyTest`
4. 在 `on_assert()` 中把 HTTP 响应转换为 `ApiResponse`
5. 用 `@StBasePyTest.data_driven` + `self.run_case(...)` 执行 YAML 用例

最小示例：

```python
from kmvpy.common.response import ApiResponse
from kmvpy.common.st import StBasePyTest, StExpect, StTestCase


class TestOrderRouter(StBasePyTest):
    def on_assert(self, resp, expected: StExpect):
        assert resp is not None, "没有任何步骤产生响应"
        assert resp.status_code == 200, f"HTTP {resp.status_code}: {resp.text}"
        expected.assert_on(ApiResponse(**resp.json()))

    @StBasePyTest.data_driven
    def test_create_order(self, user_smoke_client, testdata: StTestCase):
        self.run_case(user_smoke_client, testdata)
```

---

<a name="english"></a>

## English

This project was generated by `kmvpy create`. The actual Python project lives in the `__PY_PROJECT_NAME__/` directory.

### Quick Start

It is recommended to open the outer workspace root directory (generated root) in Cursor, rather than opening `__PY_PROJECT_NAME__/` alone. This lets you reuse the preset `.vscode/settings.json` and `.vscode/launch.json` from the generator.

First, create a virtual environment and install dependencies:

```bash
cd __PY_PROJECT_NAME__
python -m venv .venv
source .venv/bin/activate
pip install -e ".[test,sqlite]"
```

Then select the interpreter in Cursor:

1. Open the command palette
2. Run `Python: Select Interpreter`
3. Choose `__PY_PROJECT_NAME__/.venv`

Start the application:

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
python app/run.py
```

### Smoke Tests

The generated project includes the `app/st_test/` smoke test directory, covering user login, registration, and profile endpoints.

The test framework is built on:

- `pytest` — test runner
- `StBasePyTest.data_driven` — converts YAML cases into parametrized tests
- `TestClient` — calls the FastAPI app directly, no need to start a server manually
- `StExpect` — asserts only the necessary fields, suitable for smoke tests

By default, tests use `app/etc/develop/config.yaml` as the client configuration source, and construct request URLs from `service.host/service.port`.
User-related tests automatically generate a temporary SQLite configuration and database file, so they can run locally without external services.

Run all smoke tests:

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pip install -e ".[test,sqlite]"
pytest app/st_test
```

Run a single user test:

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pytest app/st_test/test_user_opt_router.py -k test_email_login -q
```

Verbose output:

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pytest app/st_test -vv
```

### Using in Cursor

Two recommended approaches:

#### 1. Built-in Terminal

The most stable approach:

```bash
cd __PY_PROJECT_NAME__
source .venv/bin/activate
pytest app/st_test -vv
```

#### 2. Test Panel

After selecting the `__PY_PROJECT_NAME__/.venv` interpreter in Cursor, you can run tests under `app/st_test` directly from the test panel.

If tests are not discovered or imports fail, check:

- Whether you opened the outer workspace root directory
- Whether the current interpreter is `__PY_PROJECT_NAME__/.venv`
- Whether `pytest` is installed
- Whether `aiosqlite` is installed

### File Convention

Each test file must have a corresponding YAML file with the same name in the same directory:

- `app/st_test/test_user_opt_router.py`
- `app/st_test/test_user_opt_router.yaml`

The top-level YAML keys must match the test method names. For example:

```python
@StBasePyTest.data_driven
def test_email_login(self, user_smoke_client, testdata: StTestCase):
    self.run_case(user_smoke_client, testdata)
```

Corresponding YAML:

```yaml
test_email_login:
  comment: User login smoke test
  case_list:
    - comment: Login with a registered account
      steps:
        - step_kid: STEP_EMAIL_LOGIN
          action: POST /api/user/email/login
          request:
            email: smoke_login@example.com
            password: "SmokePass123"
      expected:
        code: 0
```

Conventions:

- `step.action` must be written as `METHOD /uri`
- `request` maps to the JSON body for `POST`
- `request` maps to query parameters for `GET`
- `expected.data` only needs the key fields you care about

### Adding a New Smoke Test

To add a new API smoke test, follow these steps:

1. Create a new test file in `app/st_test/`, e.g. `test_order_router.py`
2. Create `test_order_router.yaml` in the same directory
3. Have your test class inherit from `StBasePyTest`
4. Convert the HTTP response to `ApiResponse` in `on_assert()`
5. Use `@StBasePyTest.data_driven` + `self.run_case(...)` to execute YAML cases

Minimal example:

```python
from kmvpy.common.response import ApiResponse
from kmvpy.common.st import StBasePyTest, StExpect, StTestCase


class TestOrderRouter(StBasePyTest):
    def on_assert(self, resp, expected: StExpect):
        assert resp is not None, "No step produced a response"
        assert resp.status_code == 200, f"HTTP {resp.status_code}: {resp.text}"
        expected.assert_on(ApiResponse(**resp.json()))

    @StBasePyTest.data_driven
    def test_create_order(self, user_smoke_client, testdata: StTestCase):
        self.run_case(user_smoke_client, testdata)
```
